### ISSUE TITLE
Launch tracking

### ISSUE THREAD

**Issue by kytrinyx** [exercism/ballerina#1]
Edit this issue to keep track of the tasks you're working on towards launch.

We have a rough guide for how to launch a track, which is a good starting point;
please ask if you have any questions or if anything is confusing!
https://github.com/exercism/docs/blob/master/language-tracks/launch/README.md

**Comment by kytrinyx** [comment]
We're working towards the launch of the [v2](https://github.com/exercism/v2-feedback/blob/master/README.md) site. I've seeded the ballerina track so you have a page to work from: https://v2.exercism.io/tracks/ballerina

I've made a note for our designer to make an icon for Ballerina for the v2 site.

**Comment by kasun04** [comment]
Fixed.
