### ISSUE TITLE
Can we fetch a custom directory as part of the 'exercism fetch' 

### ISSUE THREAD

**Issue by kasun04** [exercism/ballerina#10]
Hi @kytrinyx , 
Is it possible to configure our repo to fetch a custom directory as part of the 'exercism fetch'. In Ballerina, we have a self-contained test in each directory but to run the test we need to have a init file/directory at the top level (i.e. ~/exercism/ballerina). 
If this is not configurable, I guess it's ok to add it to the instruction on how to initiate the environment prior to running the tests.

**Comment by kytrinyx** [comment]
Does the init file/directory at the top level need to be different for every test, or can it be the same?

**Comment by kasun04** [comment]
Fixed the issue by adding a build instruction instead.
