### ISSUE TITLE
Add highlightjs support

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/ballerina#105]
Exercism uses [highlightjs](https://highlightjs.org/) for syntax highlighting. Unfortunately, there is no support for this track at the moment (see the [supported languages](https://github.com/highlightjs/highlight.js/blob/main/SUPPORTED_LANGUAGES.md)).

To properly support syntax highlighting for this track, an official grammar should be created at https://github.com/highlightjs/highlight.js/tree/main/src/languages. Note that this grammar could be relatively minimal at first and can be expanded upon at a later time.

@joshgoebel has initimate knowledge of the code base and has graciously offered to be available for any questions.

See https://github.com/exercism/v3-launch/issues/36

**Comment by joshgoebel** [comment]
If I can help, let me know.  Looks like it should be an easy enough language to highlight.

**Comment by ErikSchierboom** [comment]
That would be great. I'm fairly sure this track is unmaintained.

**Comment by ErikSchierboom** [comment]
@joshgoebel Are you still interested in looking into this? We'll have Ballerina in "Mind Shifting May" next month, as syntax highlighting would be great!

**Comment by joshgoebel** [comment]
I don't have time build it out myself but if someone else was interested and just needs a little help or a few pointers I'd be happy to help.

**Comment by BNAndras** [comment]
I was poking around the highlightjs repo since I'm about to start working on a Pyret grammar and noticed Ballerina support was added last month in https://github.com/highlightjs/highlight.js/pull/3852. Does this mean we can include syntax highlighting for the Ballerina track?

**Comment by joshgoebel** [comment]
@ErikSchierboom There you go, someone else went and built it for ya. :-)

https://github.com/highlightjs/highlightjs-ballerina

**Comment by ErikSchierboom** [comment]
That's nice of them! :D

**Comment by ErikSchierboom** [comment]
It's working: 
![Uploading image.png…]()
