### ISSUE TITLE
Adding maintainers

### ISSUE THREAD

**Issue by kytrinyx** [exercism/ballerina#146]
Hi @vordimous,

I noticed that you've been doing work on Ballerina recently.

Would it be ok if I add you to the team that has write-access to the repository? At the moment the team is empty, so you'd be the only one on it, unless you find some friends to recruit :)

**Comment by vordimous** [comment]
I would be Honored! I will ask the team if there are others.

**Comment by kytrinyx** [comment]
Yay, add the GitHub usernames of any others here, and I'll add them to the team!

**Comment by kytrinyx** [comment]
@vordimous you should have an invite 🌷 Welcome!

**Comment by vordimous** [comment]
Hi @kytrinyx, could you please add these two team members as maintainers:
https://github.com/ThisaruGuruge
https://github.com/IMS94

**Comment by ErikSchierboom** [comment]
@vordimous I can't find IMS94 in our DB, I've added Thisaru in the DB.

**Comment by kytrinyx** [comment]
@vordimous I've added both of them as maintainers. Thanks to both for joining in on the fun!

**Comment by vordimous** [comment]
Thank you @kytrinyx!

**Comment by vordimous** [comment]
@kytrinyx  I can see @IMS94 is in the approver list but @ThisaruGuruge isn't. Do they need to do something or accept an invitation?

**Comment by IMS94** [comment]
Thanks for adding me.

@vordimous probably yes. I got an invitation to this github org which I accepted. @ThisaruGuruge has to accept his invitation as well.

**Comment by ThisaruGuruge** [comment]
Hi all, sorry, I was away for the weekend (and Monday) :). Accepted the invitation. Thank you!

**Comment by ErikSchierboom** [comment]
> @vordimous I can't find IMS94 in our DB, I've added Thisaru in the DB.

I see that IMS94 has registered, so I've updated the DB too

**Comment by vordimous** [comment]
One more maintainer: @SasinduDilshara
username: dilsharasasindu

**Comment by kytrinyx** [comment]
I've sent the invite to @SasinduDilshara to join the `@exercism/ballerina` team 👍

**Comment by ErikSchierboom** [comment]
And I've added @SasinduDilshara to the DB as a maintainer.

**Comment by vordimous** [comment]
@ErikSchierboom or @kytrinyx The team is saying they can see the Ballerina exercism track but only the two "active" exercises. The "wip" exercises aren't visible to them, but they are visible to me. Do they need to be added as the contributor?

**Comment by ErikSchierboom** [comment]
They also need to be team members of the org in our DB. The problem was that they were team members before they'd joined, which is why the webhook could not update the user's team memberships in the DB. I've just manually run the syncing job and it should now work.

**Comment by kytrinyx** [comment]
Yepp! @SasinduDilshara is already a member of the team, and I've sent an invite to the other three.

Thanks, everyone, for your efforts in improving the track! It's much appreciated 💙
