### ISSUE TITLE
Is this track open to contributions of "traditional" practice exercises

### ISSUE THREAD

**Issue by glennj** [exercism/ballerina#164]
I started on this track recently and am keen to contribute.

The first few exercises have the flavour of concept exercises.

Are you maintainers open to contributions of problem-specification practice exercises to build up the track (particularly with Ballerina's #12in23 month upcoming)?

attn: @exercism/ballerina @ErikSchierboom

**Comment by glennj** [comment]
FYI I put together a `sieve` exercise if you're interested.
https://github.com/glennj/exercism-ballerina/commit/fcbe47a398cb7a3a02f10cdcea021157553c0a45

**Comment by ThisaruGuruge** [comment]
Hi @glennj Thank you and yes, we are more than happy to accept contributions. Please send a PR, we will go through it.
