### ISSUE TITLE
Upgrading infrastructure to use 2201.5.0 distribution

### ISSUE THREAD

**Issue by glennj** [exercism/ballerina#168]
In this repo
* https://github.com/exercism/ballerina/blob/main/.github/workflows/ci.yml#L18
* https://github.com/exercism/ballerina/blob/main/.github/workflows/pr.ci.yml#L17

In the test runner:
* https://github.com/exercism/ballerina-test-runner/blob/main/Dockerfile#L1

But what about all the `distribution` entries in the exercise Ballerina.toml? Do they all need to change?
* example: https://github.com/exercism/ballerina/blob/main/exercises/practice/calculator-service/Ballerina.toml#L5

**Comment by ErikSchierboom** [comment]
> But what about all the distribution entries in the exercise Ballerina.toml? Do they all need to change?

If so, we should be adding `Ballerina.toml` to the exercise's invalidator files.

**Comment by ErikSchierboom** [comment]
I got the following error when running the `raindrops` exercise:

```
 \n Compile Failed: \n WARNING [Dependencies.toml:(6:1,59:1)] Detected corrupted Dependencies.toml file. This will be updated to latest dependencies.
ERROR [Dependencies.toml:(8:1,8:34)] key 'distribution-version' not supported in schema 'ballerina'
error: compilation contains errors
```

We might not be using the latest and greatest. I think we should probably try to do that, as we don't have to worry about breaking changes much as the track hasn't been live that long.

**Comment by andrew-danieli-fj** [comment]
Hi,

I Get the following error when trying to run the "Service Invocation" task.

> Compile Failed:
> WARNING [service_invocation] Detected an attempt to compile this package using Swan Lake Update 5. However, this package was built using Swan Lake Update 4 or an older Update. To ensure compatibility, the Dependencies.toml file will be updated with the latest versions that are compatible with Update 5.
> ERROR [service_invocation.bal:(9:27,9:46)] undefined function 'brainyQuoteClient'
> error: compilation contains errors

I'm not sure if its an issue with the task runner or my code?  Any help would be appreciated.
