### ISSUE TITLE
Implement practice exercises that have been featured in previous #12in23 months

### ISSUE THREAD

**Issue by glennj** [exercism/ballerina#194]
By my reckoning, that is

- [x] binary-search
- [x] etl
- [x] largest-series-product
- [x] linked-list
- [x] protein-translation
- [x] robot-simulator
- [x] saddle-points
- [x] secret-handshake
- [ ] sum-of-multiples
- [ ] yacht

**Comment by glennj** [comment]
@ErikSchierboom I'm currently working on linked-list

**Comment by ErikSchierboom** [comment]
I have an etl pr up

**Comment by glennj** [comment]
starting largest-series-product

**Comment by glennj** [comment]
Doing robot-simulator

**Comment by glennj** [comment]
saddle-points

**Comment by glennj** [comment]
secret-handshake

**Comment by glennj** [comment]
sum-of-multiples

**Comment by glennj** [comment]
yacht
