### ISSUE TITLE
Add tokei support for Ballerina

### ISSUE THREAD

**Issue by glennj** [exercism/ballerina#243]
Tokei is the "lines of code counter" tool.

Add Ballerina configuration

https://github.com/exercism/tokei/blob/master/CONTRIBUTING.md#language-addition
https://discord.com/channels/854117591135027261/1169215168484479006

**Comment by BNAndras** [comment]
I’ll take a look at this next week.

**Comment by homersimpsons** [comment]
@glennj Looks like this can be closed:
- https://github.com/exercism/tokei/blob/511aa5800330c120531eafc006f3dc1044d23a18/languages.json#L151-L156
- https://github.com/exercism/tokei/pull/21
