### ISSUE TITLE
Ballerina - Exercism Icons  

### ISSUE THREAD

**Issue by kasun04** [exercism/ballerina#32]

**Comment by kasun04** [comment]
Request for icon is there at [.](https://github.com/exercism/website-icons/issues/10)

**Comment by kasun04** [comment]
@kytrinyx Also we may need icons for each exercise but we can do it when we have a substantial set of exercises. Are they usually created by the track maintainers?

**Comment by kytrinyx** [comment]
@kasun04 -- for exercises that come from the common pool (anything in ;problem-specifications https://github.com/exercism/problem-specifications/tree/master/exercises we get the icon for free. For any custom exercises we'll need to open issues in the https://github.com/exercism/website-icons/issues repo to ask `@nicolechalmers` to design them.

We have a subscription to the Noun Project (https://thenounproject.com/) so when opening the issues for getting icons designed it would be incredibly helpful if you do some searches there first to see if you have any ideas or suggestions.

**Comment by iHiD** [comment]
The ballerina logo is live :)

Are there any new exercise logos?
