### ISSUE TITLE
Ballerina on main tracks page? 

### ISSUE THREAD

**Issue by kasun04** [exercism/ballerina#34]
@kytrinyx Any thoughts on how we can list down Ballerina under [1]. Are we missing some requirements to be listed there? 

Thanks, 
Kasun 

[1] https://exercism.io/tracks

**Comment by kasun04** [comment]
Any thoughts @kytrinyx ?

**Comment by kytrinyx** [comment]
@kasun04 I'm so sorry I didn't see this!

There are two steps. The first is that you'll need a logo. I opened an issue a few months ago, and have pinged the issue again now: https://github.com/exercism/website-icons/issues/10

The second is a manual step where @iHiD or I need to add the track to the database for the site. I already added ballerina in the seed data for doing development work on the website (https://github.com/exercism/website/blob/4df6745b0d54c003c48021d636f0b75eb4cb169d/app/services/git/seed_tracks.rb#L11), but to get it into production we need to do the manual addition.

**Comment by iHiD** [comment]
Shall we push it live?

**Comment by kytrinyx** [comment]
I think we should add it now, even if we do not add it to the homepage yet--that will give the ballerina team a chance to test it out on the site.

**Comment by lynnlangit** [comment]
Hi all - I was hoping to show Ballerina on Exercism as a short part of my keynote at BuildStuff on Nov 14.  If the track is not yet ready, I completely understand, but just wanted to weigh in here.  Also I am interested in becoming a mentor for this track once it does launch.  It's great to see everyone's hard work getting so close to launch here!

**Comment by iHiD** [comment]
OK, so it's now live here: https://exercism.io/my/tracks/ballerina

@kasun04 Could you please just give things a general check and then if you're happy we'll launch it and publicise it? As part of that, would you be able to help recruit a few mentors please?

@lynnlangit It should be more than ready for then :)

**Comment by lynnlangit** [comment]
LGTM - I have one other potential mentor.  Is it ok to start a track with two mentors?
Also @kasun04 will there be any mentors from WS02?

**Comment by iHiD** [comment]
@kasun04 When you are ready to launch, please set `active: true` in the `config.json`, and then ping me here.

**Comment by lynnlangit** [comment]
@kasun04  - my keynote is tomorrow at 9am Vilnius time (+8 hrs to PST) - would it be possible for you to make this update before then?

**Comment by iHiD** [comment]
@lynnlangit I've done it for you :) @kasun04 I hope that wasn't an incorrect decision by me :) Pls let me know if so!

**Comment by lynnlangit** [comment]
@iHiD - thanks so much, really appreciate it!

**Comment by iHiD** [comment]
Does the Keynote get filmed? :)

**Comment by lynnlangit** [comment]
@iHiD  - the keynote was filmed, I will tweet a link when it's released.  The talk seemed to go over well.  When I told the audience about Ballerina lessons on Exercism they applauded.

I've been in 6 countries in 6 weeks.  I am home for one week, then 3 more weeks of travel.  It's my goal by mid Jan to complete all of the Ballerina lessons myself, then I can be one of the first mentors.  Would you like a mentor bio ASAP, or would you like to wait until I have time to complete all of the lessons?

**Comment by iHiD** [comment]
> I've been in 6 countries in 6 weeks. I am home for one week, then 3 more weeks of travel.

💙!!

> Would you like a mentor bio ASAP

If possible yes, but if that's too much for you to manage with with all the traveling etc, then prioritising staying sane! :)
