### ISSUE TITLE
Code snippet on about page too large

### ISSUE THREAD

**Issue by sshine** [exercism/ballerina#44]
The code snippet introduced in 3933a89d10c2e273bb4f37765c6073b5c37600b5 exceeds the bounding box on the page:

* https://exercism.io/my/tracks/ballerina

As far as I remember, it should fit 40 columns and 10 rows.

But when I kept within those bounds (using 38x9 characters) in exercism/haskell@d3d841ef21c4276f5dcdb5534e1e6f3c5d1ca4b5, this now also wraps not so nicely:

* https://exercism.io/my/tracks/haskell

It seems that one needs to stay a little more within the bounds.

In case this renders differently on different browsers, here's Chrome on Linux:

![about-ballerina](https://user-images.githubusercontent.com/50879/48776655-bfcc7380-ecd0-11e8-9954-9800765876e3.png)

**Comment by ErikSchierboom** [comment]
@exercism/ballerina Any chance we could make the snippet a bit smaller?

**Comment by ThisaruGuruge** [comment]
> @exercism/ballerina Any chance we could make the snippet a bit smaller?

We will have a look.

**Comment by homersimpsons** [comment]
@sshine Looks like there is no more code snippet on https://exercism.org/tracks/ballerina/about nor on https://exercism.org/tracks/ballerina (connected or not).

So I believe this can be closed
