### ISSUE TITLE
Can't pull Echo World Service lesson

### ISSUE THREAD

**Issue by lynnlangit** [exercism/ballerina#47]
Get this error
<img width="737" alt="screen shot 2018-11-21 at 9 40 46 am" src="https://user-images.githubusercontent.com/1609620/48858983-b6471800-ed71-11e8-99fa-2d65aa1d5e2b.png">

**Comment by kasun04** [comment]
@lynnlangit Fixed. Please have a look. Thanks a lot for reporting this.
