### ISSUE TITLE
Update lessons for 0.99 release

### ISSUE THREAD

**Issue by lynnlangit** [exercism/ballerina#49]
In reading the version release notes and mentoring a student who is working on the lessons, I am wondering what the team's plan is for updating the lessons to work with this release?

**Comment by lynnlangit** [comment]
Any update on this?

**Comment by vinok88** [comment]
I sent the PR https://github.com/exercism/ballerina/pull/50 to update the calculator exercise to v0.990.3.

**Comment by Manuri** [comment]
We've updated all the exercises.
