### ISSUE TITLE
Ready for preview mode

### ISSUE THREAD

**Issue by kasun04** [exercism/ballerina#6]
Hi @kytrinyx 

I have followed the 'Launching a new language track'[1] and completed the steps all the way to the Travis CI configuration. So, I guess the track is ready for the preview mode. Please let me know the next steps and if there are any missing tasks that we should have prior to the preview mode. 

Thanks, 
Kasun

[1] https://github.com/exercism/docs/blob/master/language-tracks/launch/README.md 
[2]

**Comment by kytrinyx** [comment]
Excellent! Here you go: https://v2.exercism.io/my/tracks/ballerina

**Comment by kasun04** [comment]
Looks like it goes to an empty page. Most of the steps that I followed are related to the existing version I guess, and I don't recall that I did any specific things for v2. Maybe that's why it's failing?

**Comment by kytrinyx** [comment]
Last week we were having trouble with updates on the v2 site, and I thought they were fixed. I'll check what's going on with that.

**Comment by kytrinyx** [comment]
Ok, I've confirmed that this is broken, and we'll be looking at fixing it before the end of the week. Sorry about the confusion!

**Comment by kasun04** [comment]
Thanks @kytrinyx . Do I have to prepare this track to be compatible with v2 in the meantime?

**Comment by kytrinyx** [comment]
You don't have to worry about compatibility with v1, just with v2 (we expect to be launching v2 in the next 3-4 weeks).

**Comment by kasun04** [comment]
Thanks. Resolving the issue as v2 related tasks are completed.
