### ISSUE TITLE
Ballerina workflow seems broken

### ISSUE THREAD

**Issue by JekoTronik** [exercism/ballerina#68]
I wanted to try Ballerina with Exercism. But I think something is broken here : 
```
$ exercism download --exercise=hello-world --track=ballerina

Downloaded to
/home/jeko/exercism/ballerina/hello-world
$ cd /home/jeko/exercism/ballerina/hello-world
$ ballerina init
$ ballerina test hello-world
Compiling tests
error: cannot find module 'hello-world'
```

Test isn't failling the right way to my opinion. Am I wrong ?

**Comment by vinok88** [comment]
I think you need to `cd` one step back into the `/home/jeko/exercism/ballerina` folder and run above `ballerina` commands. 
Modules are defined as subfolders of the project root. In your case, `hello-world` folder acts as the project root. Hence there is no such module.

Please verify and get back to us. Thank you.

**Comment by JekoTronik** [comment]
Here is what I get : 
```
$ cd /home/jeko/exercism/ballerina
$ ballerina test hello-world
error: you are trying to execute tests in a module that is not inside a project. Run `ballerina init` from /home/jeko/exercism/ballerina to initialize it as a project and then execute the tests.
```

I tried another way : 
```
$ cd /home/jeko/exercism/ballerina
$ ballerina test tests/hello_world_test.bal 
Compiling tests
    hello_world_test.bal
error:.::hello_world_test.bal:20:5: undefined function 'main'
```

**Comment by vinok88** [comment]
Please try these steps,
```
$ cd /home/jeko/exercism/ballerina
$ ballerina init
$ ballerina test hello-world
```

**Comment by JekoTronik** [comment]
Oh yeah I get it! Thank for the help. Sorry for having bother you with this.
Now I can do my exercisms!
Cheers!

**Comment by vinok88** [comment]
No worries! We are always happy to help!
