### ISSUE TITLE
Add New Members as Maintainers

### ISSUE THREAD

**Issue by praneesha** [exercism/ballerina#74]
We need to add new members bearing the below GitHub IDs as contributors of this track. Would be great if these members can have complete permissions to merge Pull Requests.

1. praneesha
2. MaryamZi
3. bhashinee
4. pubudu91
5. daneshk
6. irshadnilam
7. chamil321
8. hemikak

@kytrinyx @ErikSchierboom @lafernando  - Can you kindly give the required permissions to the above members, please?

**Comment by ErikSchierboom** [comment]
@praneesha That happens automatically when those users have been added to the [`maintainers.json`](https://github.com/exercism/ballerina/blob/master/config/maintainers.json) file.

**Comment by praneesha** [comment]
> @praneesha That happens automatically when those users have been added to the [`maintainers.json`](https://github.com/exercism/ballerina/blob/master/config/maintainers.json) file.

Updated the `maintainers.json` file via https://github.com/exercism/ballerina/pull/75.

Thanks, @ErikSchierboom.

**Comment by ErikSchierboom** [comment]
Sure!
