### ISSUE TITLE
Docs Outdated- "Ballerina init" Is No Longer a Command...

### ISSUE THREAD

**Issue by JimLynchCodes** [exercism/ballerina#76]
Hello! 

I am trying to run the tests for ballerina `hello-world` problem, but I am running into issues. I think the docs for this track are referencing an older version of the cli because it recommends running `ballerina init` which is not a valid command anymore...

I have written more details about this here: https://github.com/ballerina-platform/ballerina-lang/issues/20939 Hopefully, we can figure this out and update the exercism ballerina docs so it's easier for the next students!

**Comment by ErikSchierboom** [comment]
The docs have been updated.
